#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finsa.Caravan.Mvc.Controls.PageElements
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 4 "..\..\Controls\PageElements\CaravanPageHeader_.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class CaravanPageHeader_
    {

public static System.Web.WebPages.HelperResult FlexPageHeader(this HtmlHelper htmlHelper) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 6 "..\..\Controls\PageElements\CaravanPageHeader_.cshtml"
                                                    


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <span></span>\r\n");



#line 9 "..\..\Controls\PageElements\CaravanPageHeader_.cshtml"


#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
