#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEX.Web.MVC.Layouts
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Layouts\Common_.cshtml"
    using FLEX.Web.MVC.Layouts;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Layouts/Common_.cshtml")]
    public partial class Common_ : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Common_()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n   <head>\r\n   \r\n      <script type=\"text/javascript\"" +
" src=\"");


            
            #line 11 "..\..\Layouts\Common_.cshtml"
                                      Write(Common.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/popupHandler.min.js");


            
            #line 11 "..\..\Layouts\Common_.cshtml"
                                                                                    Write(Common.NoCacheTag);

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n   </head>\r\n   \r\n   <body>\r\n      COMMON\r\n      ");


            
            #line 16 "..\..\Layouts\Common_.cshtml"
 Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n   </body>\r\n\r\n</html>");


        }
    }
}
#pragma warning restore 1591
