#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEX.Web.MVC.Layouts
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Layouts\FlexSharedLayout_.cshtml"
    using FLEX.Web.MVC.Layouts;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Layouts/FlexSharedLayout_.cshtml")]
    public partial class FlexSharedLayout_ : System.Web.Mvc.WebViewPage<dynamic>
    {
        public FlexSharedLayout_()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");


WriteLiteral(@"
<!DOCTYPE html>

<html>
   <head>
      <!-- Required for IE compatibility -->
      <meta http-equiv=""X-UA-Compatible"" content=""IE=11; IE=10; IE=9; IE=EDGE"" />
      <meta http-equiv=""Content-Type"" content=""text/html; charset=utf-8"" />
      <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"" />

      <!-- CSS for Bootstrap, respond.js must be AFTER this CSS; ""DoNotCacheTag"" is needed to avoid issues with IE9 -->
      <link href=""");


            
            #line 16 "..\..\Layouts\FlexSharedLayout_.cshtml"
              Write(FlexSharedLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Styles/fonts.min.css");


            
            #line 16 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                                               Write(FlexSharedLayout.DoNotCacheTag);

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" media=\"screen\" />\r\n      <link href=\"");


            
            #line 17 "..\..\Layouts\FlexSharedLayout_.cshtml"
              Write(FlexSharedLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Styles/bootstrap.min.css");


            
            #line 17 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                                                   Write(FlexSharedLayout.DoNotCacheTag);

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" media=\"screen\" />\r\n      <!--[if lt IE 9]>  \r\n         <script" +
" src=\"");


            
            #line 19 "..\..\Layouts\FlexSharedLayout_.cshtml"
                  Write(FlexSharedLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/html5shiv.min.js\"></script>\r\n         <script src=\"");


            
            #line 20 "..\..\Layouts\FlexSharedLayout_.cshtml"
                  Write(FlexSharedLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/respond.min.js\"></script>\r\n      <![endif]-->\r\n      \r\n      <script typ" +
"e=\"text/javascript\" src=\"");


            
            #line 23 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexSharedLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/jquery.min.js\"></script>\r\n      <script type=\"text/javascript\" src=\"");


            
            #line 24 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexSharedLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/jquery-ui.min.js\"></script>\r\n      <script type=\"text/javascript\" src=\"");


            
            #line 25 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexSharedLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/underscore.min.js\"></script>\r\n      <script type=\"text/javascript\" src=\"" +
"");


            
            #line 26 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexSharedLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/backbone.min.js\"></script>\r\n      <script type=\"text/javascript\" src=\"");


            
            #line 27 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexSharedLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/bootstrap.min.js\"></script>\r\n      <script type=\"text/javascript\" src=\"");


            
            #line 28 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexSharedLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/bootstrap-hover-dropdown.min.js\"></script>\r\n      \r\n      ");


            
            #line 30 "..\..\Layouts\FlexSharedLayout_.cshtml"
 Write(RenderSection("HeadSection"));

            
            #line default
            #line hidden
WriteLiteral("\r\n   </head>\r\n   \r\n   <body>\r\n      ");


            
            #line 34 "..\..\Layouts\FlexSharedLayout_.cshtml"
 Write(RenderSection("BodySection"));

            
            #line default
            #line hidden
WriteLiteral("\r\n   </body>\r\n\r\n</html>");


        }
    }
}
#pragma warning restore 1591
