#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEX.Web.MVC.Controls.ValueHolders
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class AutoComplete
    {

public static System.Web.WebPages.HelperResult Create(string text) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 4 "..\..\Controls\ValueHolders\AutoComplete.cshtml"
                             


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <span>");



#line 6 "..\..\Controls\ValueHolders\AutoComplete.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</span>\r\n");



#line 7 "..\..\Controls\ValueHolders\AutoComplete.cshtml"


#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
