#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEX.Web.MVC.Controls.ValueHolders
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 4 "..\..\Controls\ValueHolders\BootstrapDatePicker_.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Controls\ValueHolders\BootstrapDatePicker_.cshtml"
    using FLEX.Web.MVC.Controls.ValueHolders;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Controls\ValueHolders\BootstrapDatePicker_.cshtml"
    using PommaLabs.GRAMPA.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class BootstrapDatePicker_
    {

public static System.Web.WebPages.HelperResult BootstrapDatePicker(this HtmlHelper htmlHelper, BootstrapDatePickerOptions options) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 8 "..\..\Controls\ValueHolders\BootstrapDatePicker_.cshtml"
                                                                                             


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "     <div ID=\"");



#line 10 "..\..\Controls\ValueHolders\BootstrapDatePicker_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ID);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "-container\" class=\"input-group date\">\r\n         <input ID=\"");



#line 11 "..\..\Controls\ValueHolders\BootstrapDatePicker_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ID);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" type=\"text\" runat=\"server\" class=\"form-control\" />\r\n         <span class=\"input" +
"-group-addon\"><i class=\"glyphicon glyphicon-th\"></i></span>\r\n      </div>\r\n");



#line 14 "..\..\Controls\ValueHolders\BootstrapDatePicker_.cshtml"
   
   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <script type=\"text/javascript\">\r\n       $(\'#");



#line 17 "..\..\Controls\ValueHolders\BootstrapDatePicker_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ID);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "-container\').datepicker({\r\n          format:  \"");



#line 18 "..\..\Controls\ValueHolders\BootstrapDatePicker_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.DateFormat);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\",\r\n          weekStart: 1,\r\n          startView: ");



#line 20 "..\..\Controls\ValueHolders\BootstrapDatePicker_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Convert.ToByte(options.StartView));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ",\r\n          minViewMode:");



#line 21 "..\..\Controls\ValueHolders\BootstrapDatePicker_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Convert.ToByte(options.MinView));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ",\r\n          todayBtn: \"linked\",\r\n          autoclose: true,\r\n          todayHigh" +
"light: true\r\n       });\r\n      \r\n       $(\"#");



#line 27 "..\..\Controls\ValueHolders\BootstrapDatePicker_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ID);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\").on(\'changeDate.datepicker\', function(event) {\r\n          ");



#line 28 "..\..\Controls\ValueHolders\BootstrapDatePicker_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ChangeDate);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "(event);\r\n             });\r\n      </script> \r\n");



#line 31 "..\..\Controls\ValueHolders\BootstrapDatePicker_.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
