//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEX.Sample.WebUI {
    
    
    public partial class CandidateList {
        
        /// <summary>
        /// divShownSearchCriteria control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divShownSearchCriteria;
        
        /// <summary>
        /// autosuggestFullName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.AutoSuggest autosuggestFullName;
        
        /// <summary>
        /// autosuggestEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.AutoSuggest autosuggestEmail;
        
        /// <summary>
        /// ctrlGendId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.CollapsibleCheckBoxList ctrlGendId;
        
        /// <summary>
        /// ctrlSchlId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.CollapsibleCheckBoxList ctrlSchlId;
        
        /// <summary>
        /// flexTestSpinner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.NumericSpinner flexTestSpinner;
        
        /// <summary>
        /// updDataGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel updDataGrid;
        
        /// <summary>
        /// fdtgCandidates control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.WebForms.UserControls.DataGrid fdtgCandidates;
        
        /// <summary>
        /// btnError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.ImageButton btnError;
        
        /// <summary>
        /// btnLog control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.ImageButton btnLog;
        
        /// <summary>
        /// flexOnOffSwitch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.OnOffSwitch flexOnOffSwitch;
        
        /// <summary>
        /// flexExportList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.ExportList flexExportList;
        
        /// <summary>
        /// flexReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.ImageButton flexReport;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new FLEX.Web.MasterPages.Base Master {
            get {
                return ((FLEX.Web.MasterPages.Base)(base.Master));
            }
        }
    }
}
