#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 4 "..\..\Controls\ValueHolders\BootstrapSwitch_.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Controls\ValueHolders\BootstrapSwitch_.cshtml"
    using Finsa.Caravan.Common.Utilities.Extensions;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Controls\ValueHolders\BootstrapSwitch_.cshtml"
    using Finsa.Caravan.Mvc.Controls.ValueHolders;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class _Controls_ValueHolders_BootstrapSwitch__cshtml
    {

public static System.Web.WebPages.HelperResult BootstrapSwitch(this HtmlHelper htmlHelper, BootstrapSwitchOptions options)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 9 "..\..\Controls\ValueHolders\BootstrapSwitch_.cshtml"
 


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "   <input id=\"");



#line 11 "..\..\Controls\ValueHolders\BootstrapSwitch_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ID);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" type=\"checkbox\" />\r\n");



#line 12 "..\..\Controls\ValueHolders\BootstrapSwitch_.cshtml"


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "   <script type=\"text/javascript\">\r\n      $(document).ready(function() {\r\n       " +
"  $(\"#");



#line 15 "..\..\Controls\ValueHolders\BootstrapSwitch_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ID);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\").bootstrapSwitch({\r\n            state: ");



#line 16 "..\..\Controls\ValueHolders\BootstrapSwitch_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.State.ToJavaScriptBoolean());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ",\r\n            size: \"");



#line 17 "..\..\Controls\ValueHolders\BootstrapSwitch_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.SizeString);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"\r\n         });\r\n\r\n         $(\"#");



#line 20 "..\..\Controls\ValueHolders\BootstrapSwitch_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ID);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\").on(\'switchChange.bootstrapSwitch\', function(event, state) {\r\n            // Cu" +
"stom handlers\r\n            ");



#line 22 "..\..\Controls\ValueHolders\BootstrapSwitch_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.OnChange);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "(event, state);\r\n         \r\n            // Search criteria handling\r\n            " +
"var searchCriteria = getSearchCriteria(\"");



#line 25 "..\..\Controls\ValueHolders\BootstrapSwitch_.cshtml"
         WebViewPage.WriteTo(@__razor_helper_writer, options.SearchCriteriaID);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\");\r\n            if (searchCriteria !== undefined) {\r\n               var criteria" +
" = searchCriteria.get(\"criteria\");\r\n               criteria[\"");



#line 28 "..\..\Controls\ValueHolders\BootstrapSwitch_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.SafeID);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"] = state;\r\n               searchCriteria.set({ criteria: criteria });\r\n        " +
"    }\r\n         });\r\n      });\r\n   </script>\r\n");



#line 34 "..\..\Controls\ValueHolders\BootstrapSwitch_.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
