//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finsa.Caravan.WebForms.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Finsa.Caravan.WebForms.Core.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No report name has been specified in the GET parameters..
        /// </summary>
        internal static string Pages_DynamicReportViewer_MissingReportName {
            get {
                return ResourceManager.GetString("Pages_DynamicReportViewer_MissingReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the IErrorManager implementation. See inner exception for more details..
        /// </summary>
        internal static string TopLevel_ErrorManager_ErrorLoadingType {
            get {
                return ResourceManager.GetString("TopLevel_ErrorManager_ErrorLoadingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the IPageManager implementation. See inner exception for more details..
        /// </summary>
        internal static string TopLevel_PageManager_ErrorLoadingType {
            get {
                return ResourceManager.GetString("TopLevel_PageManager_ErrorLoadingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the ISecurityRepository implementation. See inner exception for more details..
        /// </summary>
        internal static string TopLevel_SecurityManager_ErrorLoadingType {
            get {
                return ResourceManager.GetString("TopLevel_SecurityManager_ErrorLoadingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified XML lookup field must not be neither null nor empty..
        /// </summary>
        internal static string UserControls_AutoSuggest_NullOrEmptyLookupBy {
            get {
                return ResourceManager.GetString("UserControls_AutoSuggest_NullOrEmptyLookupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified XML lookup file must not be neither null nor empty..
        /// </summary>
        internal static string UserControls_AutoSuggest_NullOrEmptyXmlLookup {
            get {
                return ResourceManager.GetString("UserControls_AutoSuggest_NullOrEmptyXmlLookup", resourceCulture);
            }
        }
    }
}
