#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEX.Web.MVC.Controls.DataVisualization
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 4 "..\..\Controls\DataVisualization\FlexDataGrid_.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Controls\DataVisualization\FlexDataGrid_.cshtml"
    using FLEX.Web.MVC.Controls.DataVisualization;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Controls\DataVisualization\FlexDataGrid_.cshtml"
    using PagedList.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class FlexDataGrid_
    {

public static System.Web.WebPages.HelperResult FlexDataGrid(this System.Web.Mvc.HtmlHelper htmlHelper, FlexDataGridOptions options) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 8 "..\..\Controls\DataVisualization\FlexDataGrid_.cshtml"
                                                                                              


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "   <table id=\"");



#line 10 "..\..\Controls\DataVisualization\FlexDataGrid_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ID);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" class=\"table table-striped table-bordered table-condensed table-hover\">\r\n      " +
"<thead>\r\n");



#line 12 "..\..\Controls\DataVisualization\FlexDataGrid_.cshtml"
          foreach (var column in options.Columns)
         {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <th>");



#line 14 "..\..\Controls\DataVisualization\FlexDataGrid_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, column.Header);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</th>\r\n");



#line 15 "..\..\Controls\DataVisualization\FlexDataGrid_.cshtml"
         }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "      </thead>\r\n      \r\n      <tbody>\r\n         \r\n      </tbody>\r\n   </table>\r\n");



#line 22 "..\..\Controls\DataVisualization\FlexDataGrid_.cshtml"
   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, @"   <div class=""row"">
      <div class=""col-xs-4 text-left"">
         Count
      </div>
      <div class=""col-xs-4 text-center"">
         ???
      </div>
      <div class=""col-xs-4 text-right"">
         <!-- Outputs a paging control that lets the user navigation to the previous page, next page, etc -->
         ");



#line 32 "..\..\Controls\DataVisualization\FlexDataGrid_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlHelper.PagedListPager(@options.PagedItems, page => ""));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n      </div>\r\n   </div>\r\n");



#line 35 "..\..\Controls\DataVisualization\FlexDataGrid_.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
