//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEX.Web.Pages {
    
    
    public partial class CacheOverview {
        
        /// <summary>
        /// fdtgCache control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.WebControls.DataGrid fdtgCache;
        
        /// <summary>
        /// btnRefresh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.ImageButton btnRefresh;
        
        /// <summary>
        /// btnClear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.ImageButton btnClear;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new FLEX.Web.MasterPages.DataView Master {
            get {
                return ((FLEX.Web.MasterPages.DataView)(base.Master));
            }
        }
    }
}
