//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEX.Web.Pages {
    
    
    public partial class DynamicReportViewer {
        
        /// <summary>
        /// fdtgReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.DataGrid fdtgReport;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new FLEX.Web.MasterPages.VerticalSearch Master {
            get {
                return ((FLEX.Web.MasterPages.VerticalSearch)(base.Master));
            }
        }
    }
}
