//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finsa.Caravan.WebForms.Pages {
    
    
    public partial class SecGroupList {
        
        /// <summary>
        /// crvnGroupsLkp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.AutoSuggest crvnGroupsLkp;
        
        /// <summary>
        /// fdtgGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.WebForms.UserControls.DataGrid fdtgGroups;
        
        /// <summary>
        /// btnInsert control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.ImageButton btnInsert;
        
        /// <summary>
        /// hiddenRefresh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.HiddenTrigger hiddenRefresh;
        
        /// <summary>
        /// hiddenDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FLEX.Web.UserControls.Ajax.HiddenTrigger hiddenDelete;
        
        /// <summary>
        /// groupNameToBeDeleted control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField groupNameToBeDeleted;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new FLEX.Web.MasterPages.VerticalSearch Master {
            get {
                return ((FLEX.Web.MasterPages.VerticalSearch)(base.Master));
            }
        }
    }
}
