#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEX.Web.MVC.Controls.PageElements
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 4 "..\..\Controls\PageElements\FlexMenuBar_.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Controls\PageElements\FlexMenuBar_.cshtml"
    using FLEX.Web.MVC.Controls.PageElements;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class FlexMenuBar_
    {

public static System.Web.WebPages.HelperResult FlexMenuBar(this HtmlHelper htmlHelper) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 10 "..\..\Controls\PageElements\FlexMenuBar_.cshtml"
                                                 



#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " <style>\r\n  ");


WebViewPage.WriteLiteralTo(@__razor_helper_writer, "@media (min-width: 768px) {\r\n      .navbar-nav .caret { display: none; }\r\n\r\n     " +
" .navbar-nav .open ul { display: none; }\r\n\r\n      .navbar-default .navbar-nav > " +
".open > a,\r\n      .navbar-default .navbar-nav > .open > a:hover,\r\n      .navbar-" +
"default .navbar-nav > .open > a:focus,\r\n      .navbar-default .navbar-nav > .act" +
"ive > a,\r\n      .navbar-default .navbar-nav > .active > a:hover,\r\n      .navbar-" +
"default .navbar-nav > .active > a:focus { background: none; }\r\n\r\n      .navbar-i" +
"nverse .navbar-nav > .open > a,\r\n      .navbar-inverse .navbar-nav > .open > a:h" +
"over,\r\n      .navbar-inverse .navbar-nav > .open > a:focus,\r\n      .navbar-inver" +
"se .navbar-nav > .active > a,\r\n      .navbar-inverse .navbar-nav > .active > a:h" +
"over,\r\n      .navbar-inverse .navbar-nav > .active > a:focus { background: none;" +
" }\r\n\r\n      .navbar-default .navbar-nav > .hovernav:hover > a,\r\n      .navbar-de" +
"fault .navbar-nav > .hovernav:hover > a:hover,\r\n      .navbar-default .navbar-na" +
"v > .hovernav:hover > a:focus { background: transparent; }\r\n\r\n      .navbar-inve" +
"rse .navbar-nav > .hovernav:hover > a,\r\n      .navbar-inverse .navbar-nav > .hov" +
"ernav:hover > a:hover,\r\n      .navbar-inverse .navbar-nav > .hovernav:hover > a:" +
"focus { background: transparent; }\r\n\r\n      .navbar-nav .hovernav:hover > .dropd" +
"own-menu { display: block; }\r\n   }\r\n\r\n\r\n   .dropdown-submenu { position: relativ" +
"e; }\r\n\r\n   .dropdown-submenu > .dropdown-menu {\r\n      top: 0;\r\n      left: 100%" +
";\r\n      margin-top: -6px;\r\n      margin-left: -1px;\r\n      -webkit-border-radiu" +
"s: 0 6px 6px 6px;\r\n      -moz-border-radius: 0 6px 6px 6px;\r\n      border-radius" +
": 0 6px 6px 6px;\r\n   }\r\n\r\n   .dropdown-submenu:hover > .dropdown-menu { display:" +
" block; }\r\n\r\n   .dropdown-submenu > a:after {\r\n      display: block;\r\n      cont" +
"ent: \" \";\r\n      float: right;\r\n      width: 0;\r\n      height: 0;\r\n      border-" +
"color: transparent;\r\n      border-style: solid;\r\n      border-width: 5px 0 5px 5" +
"px;\r\n      border-left-color: #cccccc;\r\n      margin-top: 5px;\r\n      margin-rig" +
"ht: -10px;\r\n   }\r\n\r\n   .dropdown-submenu:hover > a:after { border-left-color: #f" +
"fffff; }\r\n\r\n   .dropdown-submenu .pull-left { float: none; }\r\n\r\n   .dropdown-sub" +
"menu.pull-left > .dropdown-menu {\r\n      left: -100%;\r\n      margin-left: 10px;\r" +
"\n      -webkit-border-radius: 6px 0 6px 6px;\r\n      -moz-border-radius: 6px 0 6p" +
"x 6px;\r\n      border-radius: 6px 0 6px 6px;\r\n   }\r\n</style>\r\n");



#line 85 "..\..\Controls\PageElements\FlexMenuBar_.cshtml"

   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, @"<nav>
   <div id=""menuBar"" class=""navbar navbar-default navbar-fixed-top"">
      <div class=""container-fluid"">
         <div class=""navbar-header"">
            <button type=""button"" class=""navbar-toggle"" data-toggle=""collapse"" data-target=""#menuBar-collapse"">
               <span class=""icon-bar""></span>
               <span class=""icon-bar""></span>
               <span class=""icon-bar""></span>
            </button>
            <a class=""navbar-brand"" href=""#"" onclick=""<%= WebSettings.UserControls_MenuBar_BrandClick %>"">
               <img src='<%= Head.MyFlexPath %>/Images/logo-menubar.png' class='logo' alt='Logo' />&nbsp;<%= FLEX.Common.Configuration.Instance.ApplicationName %>
            </a>
         </div>
         <div id=""menuBar-collapse"" class=""navbar-collapse collapse"">
            <ul class=""nav navbar-nav"" id=""ul_menu"" runat=""server"">
                  ");



#line 102 "..\..\Controls\PageElements\FlexMenuBar_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, new HtmlString(FlexMenuBarHelper.GetMenuFromService().ToString()));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, @"
            </ul>
            <ul class=""nav navbar-nav navbar-right"">
               <li>
                  <a href=""#"" onclick=""<%= WebSettings.UserControls_MenuBar_HomeClick %>"">
                     <span class=""glyphicon glyphicon-home padded-icon""></span>Home
                  </a>
               </li>
               <li>
                  <a href=""#"" onclick=""<%= WebSettings.UserControls_MenuBar_LogoutClick %>"">
                     <span class=""glyphicon glyphicon-circle-arrow-left padded-icon""></span>Logout
                  </a>
               </li>
               <li>
                  <a href=""#"" onclick=""<%= WebSettings.UserControls_MenuBar_InfoClick %>"">
                     <span class=""glyphicon glyphicon-info-sign padded-icon""></span>Info
                  </a>
               </li>
            </ul>
         </div>
      </div>
   </div>
</nav>
");



#line 125 "..\..\Controls\PageElements\FlexMenuBar_.cshtml"
   

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
