//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

// If you use this template inside a _portable_ class library,
// then you should define the PORTABLE conditional compilation symbol
// in order to enable the creation of some necessary stub classes.
#if PORTABLE

namespace System
{
    /// <summary>
    ///   Fake, this is used only to allow serialization on portable platforms.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum, AllowMultiple = true, Inherited = false)]
    internal sealed class SerializableAttribute : Attribute
    {
        // This does nothing and should do nothing.
    }
}

#endif

namespace Finsa.Caravan.Common.XmlSchemas.MenuEntries {
    
    
    /// <summary>
    ///   Automatically generated XML type mapping for Item.
    /// </summary>
    /// <remarks>
    ///   This is an automaticaly generated type, please do not edit it.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Finsa.Caravan.Common.XmlSchemas.MenuEntries")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="Finsa.Caravan.Common.XmlSchemas.MenuEntries", IsNullable=false)]
    public partial class Item {
        
        private ItemGroup groupField;
        
        private string[] textField;
        
        private string idField;
        
        private string captionField;
        
        private string enabledField;
        
        private string clientCallField;
        
        private string typeField;
        
        private string uRLField;
        
        /// <summary>
        ///   Gets or sets Group.
        /// </summary>
        public ItemGroup Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <summary>
        ///   Gets or sets Text.
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <summary>
        ///   Gets or sets ID.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <summary>
        ///   Gets or sets Caption.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
            }
        }
        
        /// <summary>
        ///   Gets or sets Enabled.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <summary>
        ///   Gets or sets ClientCall.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClientCall {
            get {
                return this.clientCallField;
            }
            set {
                this.clientCallField = value;
            }
        }
        
        /// <summary>
        ///   Gets or sets Type.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <summary>
        ///   Gets or sets URL.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <summary>
    ///   Automatically generated XML type mapping for ItemGroup.
    /// </summary>
    /// <remarks>
    ///   This is an automaticaly generated type, please do not edit it.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Finsa.Caravan.Common.XmlSchemas.MenuEntries")]
    public partial class ItemGroup {
        
        private Item[] itemField;
        
        private string layoutField;
        
        /// <summary>
        ///   Gets or sets Item.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Item")]
        public Item[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <summary>
        ///   Gets or sets Layout.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Layout {
            get {
                return this.layoutField;
            }
            set {
                this.layoutField = value;
            }
        }
    }
    
    /// <summary>
    ///   Automatically generated XML type mapping for Menu.
    /// </summary>
    /// <remarks>
    ///   This is an automaticaly generated type, please do not edit it.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Finsa.Caravan.Common.XmlSchemas.MenuEntries")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="Finsa.Caravan.Common.XmlSchemas.MenuEntries", IsNullable=false)]
    public partial class Menu {
        
        private Item[] groupField;
        
        private string layoutField;
        
        private string openOnClickField;
        
        /// <summary>
        ///   Gets or sets Group.
        /// </summary>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable=false)]
        public Item[] Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <summary>
        ///   Gets or sets Layout.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Layout {
            get {
                return this.layoutField;
            }
            set {
                this.layoutField = value;
            }
        }
        
        /// <summary>
        ///   Gets or sets OpenOnClick.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OpenOnClick {
            get {
                return this.openOnClickField;
            }
            set {
                this.openOnClickField = value;
            }
        }
    }
}
