//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finsa.Caravan.ReportingService.Reports.Sample {
    
    
    public partial class Sample {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Finsa.Caravan.ReportingService.Report Master {
            get {
                return ((Finsa.Caravan.ReportingService.Report)(base.Master));
            }
        }
    }
}
