//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEX.Web {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FLEX.Web.XmlSettings.AjaxLookup")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="FLEX.Web.XmlSettings.AjaxLookup", IsNullable=false)]
    public partial class AjaxLookupData {
        
        private AjaxLookupDataLookupBy[] lookupByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LookupBy")]
        public AjaxLookupDataLookupBy[] LookupBy {
            get {
                return this.lookupByField;
            }
            set {
                this.lookupByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FLEX.Web.XmlSettings.AjaxLookup")]
    public partial class AjaxLookupDataLookupBy {
        
        private string suggestionFieldField;
        
        private string keyFieldField;
        
        private string descriptionFieldField;
        
        private string sortFieldField;
        
        private string lookupQueryField;
        
        /// <remarks/>
        public string SuggestionField {
            get {
                return this.suggestionFieldField;
            }
            set {
                this.suggestionFieldField = value;
            }
        }
        
        /// <remarks/>
        public string KeyField {
            get {
                return this.keyFieldField;
            }
            set {
                this.keyFieldField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptionField {
            get {
                return this.descriptionFieldField;
            }
            set {
                this.descriptionFieldField = value;
            }
        }
        
        /// <remarks/>
        public string SortField {
            get {
                return this.sortFieldField;
            }
            set {
                this.sortFieldField = value;
            }
        }
        
        /// <remarks/>
        public string LookupQuery {
            get {
                return this.lookupQueryField;
            }
            set {
                this.lookupQueryField = value;
            }
        }
    }
}
namespace FLEX.Web {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FLEX.Web.XmlSettings.Lookup")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="FLEX.Web.XmlSettings.Lookup", IsNullable=false)]
    public partial class LookupData {
        
        private LookupDataDataColumn[] dataColumnsField;
        
        private string lookupQueryField;
        
        private string defaultSortField;
        
        private bool allowCancelField;
        
        private bool allowCancelFieldSpecified;
        
        private bool disableFirstSearchField;
        
        private bool disableFirstSearchFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DataColumn", IsNullable=false)]
        public LookupDataDataColumn[] DataColumns {
            get {
                return this.dataColumnsField;
            }
            set {
                this.dataColumnsField = value;
            }
        }
        
        /// <remarks/>
        public string LookupQuery {
            get {
                return this.lookupQueryField;
            }
            set {
                this.lookupQueryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultSort {
            get {
                return this.defaultSortField;
            }
            set {
                this.defaultSortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AllowCancel {
            get {
                return this.allowCancelField;
            }
            set {
                this.allowCancelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowCancelSpecified {
            get {
                return this.allowCancelFieldSpecified;
            }
            set {
                this.allowCancelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DisableFirstSearch {
            get {
                return this.disableFirstSearchField;
            }
            set {
                this.disableFirstSearchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisableFirstSearchSpecified {
            get {
                return this.disableFirstSearchFieldSpecified;
            }
            set {
                this.disableFirstSearchFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FLEX.Web.XmlSettings.Lookup")]
    public partial class LookupDataDataColumn {
        
        private string typeField;
        
        private string dataFieldField;
        
        private string sortExpressionField;
        
        private string headerTextField;
        
        private string returnElementField;
        
        private string dataTypeField;
        
        private short widthField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string DataField {
            get {
                return this.dataFieldField;
            }
            set {
                this.dataFieldField = value;
            }
        }
        
        /// <remarks/>
        public string SortExpression {
            get {
                return this.sortExpressionField;
            }
            set {
                this.sortExpressionField = value;
            }
        }
        
        /// <remarks/>
        public string HeaderText {
            get {
                return this.headerTextField;
            }
            set {
                this.headerTextField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnElement {
            get {
                return this.returnElementField;
            }
            set {
                this.returnElementField = value;
            }
        }
        
        /// <remarks/>
        public string DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        public short Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
    }
}
namespace FLEX.Web {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FLEX.Web.XmlSettings.MenuBar")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="FLEX.Web.XmlSettings.MenuBar", IsNullable=false)]
    public partial class Item {
        
        private ItemGroup groupField;
        
        private string[] textField;
        
        private string idField;
        
        private string captionField;
        
        private string enabledField;
        
        private string itemWidthField;
        
        private string clientCallField;
        
        private string typeField;
        
        private sbyte separatorHeightField;
        
        private bool separatorHeightFieldSpecified;
        
        private short separatorWidthField;
        
        private bool separatorWidthFieldSpecified;
        
        private string uRLField;
        
        /// <remarks/>
        public ItemGroup Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemWidth {
            get {
                return this.itemWidthField;
            }
            set {
                this.itemWidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClientCall {
            get {
                return this.clientCallField;
            }
            set {
                this.clientCallField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte SeparatorHeight {
            get {
                return this.separatorHeightField;
            }
            set {
                this.separatorHeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeparatorHeightSpecified {
            get {
                return this.separatorHeightFieldSpecified;
            }
            set {
                this.separatorHeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short SeparatorWidth {
            get {
                return this.separatorWidthField;
            }
            set {
                this.separatorWidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeparatorWidthSpecified {
            get {
                return this.separatorWidthFieldSpecified;
            }
            set {
                this.separatorWidthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FLEX.Web.XmlSettings.MenuBar")]
    public partial class ItemGroup {
        
        private Item[] itemField;
        
        private string layoutField;
        
        private sbyte offsetXField;
        
        private bool offsetXFieldSpecified;
        
        private sbyte offsetYField;
        
        private bool offsetYFieldSpecified;
        
        private string filterField;
        
        private string filter_DropShadow_ColorField;
        
        private sbyte filter_DropShadow_OffsetXField;
        
        private bool filter_DropShadow_OffsetXFieldSpecified;
        
        private sbyte filter_DropShadow_OffsetYField;
        
        private bool filter_DropShadow_OffsetYFieldSpecified;
        
        private string transitionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item")]
        public Item[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Layout {
            get {
                return this.layoutField;
            }
            set {
                this.layoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte OffsetX {
            get {
                return this.offsetXField;
            }
            set {
                this.offsetXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetXSpecified {
            get {
                return this.offsetXFieldSpecified;
            }
            set {
                this.offsetXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte OffsetY {
            get {
                return this.offsetYField;
            }
            set {
                this.offsetYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetYSpecified {
            get {
                return this.offsetYFieldSpecified;
            }
            set {
                this.offsetYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Filter_DropShadow_Color {
            get {
                return this.filter_DropShadow_ColorField;
            }
            set {
                this.filter_DropShadow_ColorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte Filter_DropShadow_OffsetX {
            get {
                return this.filter_DropShadow_OffsetXField;
            }
            set {
                this.filter_DropShadow_OffsetXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Filter_DropShadow_OffsetXSpecified {
            get {
                return this.filter_DropShadow_OffsetXFieldSpecified;
            }
            set {
                this.filter_DropShadow_OffsetXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte Filter_DropShadow_OffsetY {
            get {
                return this.filter_DropShadow_OffsetYField;
            }
            set {
                this.filter_DropShadow_OffsetYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Filter_DropShadow_OffsetYSpecified {
            get {
                return this.filter_DropShadow_OffsetYFieldSpecified;
            }
            set {
                this.filter_DropShadow_OffsetYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Transition {
            get {
                return this.transitionField;
            }
            set {
                this.transitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="FLEX.Web.XmlSettings.MenuBar")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="FLEX.Web.XmlSettings.MenuBar", IsNullable=false)]
    public partial class Menu {
        
        private Item[] groupField;
        
        private string layoutField;
        
        private string menuItemCssClassField;
        
        private string menuItemClickCssClassField;
        
        private string menuItemOverCssClassField;
        
        private string defaultGroupCssClassField;
        
        private string defaultItemCssClassField;
        
        private string defaultItemOverCssClassField;
        
        private string menuCssClassField;
        
        private string defaultDisabledItemCssClassField;
        
        private sbyte menuItemWidthField;
        
        private bool menuItemWidthFieldSpecified;
        
        private string scriptPathField;
        
        private string imagePathField;
        
        private string cssFileField;
        
        private string openOnClickField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable=false)]
        public Item[] Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Layout {
            get {
                return this.layoutField;
            }
            set {
                this.layoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MenuItemCssClass {
            get {
                return this.menuItemCssClassField;
            }
            set {
                this.menuItemCssClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MenuItemClickCssClass {
            get {
                return this.menuItemClickCssClassField;
            }
            set {
                this.menuItemClickCssClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MenuItemOverCssClass {
            get {
                return this.menuItemOverCssClassField;
            }
            set {
                this.menuItemOverCssClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultGroupCssClass {
            get {
                return this.defaultGroupCssClassField;
            }
            set {
                this.defaultGroupCssClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultItemCssClass {
            get {
                return this.defaultItemCssClassField;
            }
            set {
                this.defaultItemCssClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultItemOverCssClass {
            get {
                return this.defaultItemOverCssClassField;
            }
            set {
                this.defaultItemOverCssClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MenuCssClass {
            get {
                return this.menuCssClassField;
            }
            set {
                this.menuCssClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultDisabledItemCssClass {
            get {
                return this.defaultDisabledItemCssClassField;
            }
            set {
                this.defaultDisabledItemCssClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte MenuItemWidth {
            get {
                return this.menuItemWidthField;
            }
            set {
                this.menuItemWidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MenuItemWidthSpecified {
            get {
                return this.menuItemWidthFieldSpecified;
            }
            set {
                this.menuItemWidthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ScriptPath {
            get {
                return this.scriptPathField;
            }
            set {
                this.scriptPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ImagePath {
            get {
                return this.imagePathField;
            }
            set {
                this.imagePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CssFile {
            get {
                return this.cssFileField;
            }
            set {
                this.cssFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OpenOnClick {
            get {
                return this.openOnClickField;
            }
            set {
                this.openOnClickField = value;
            }
        }
    }
}
