#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finsa.Caravan.Mvc.Layouts
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Layouts\FlexSharedLayout_.cshtml"
    using FLEX.Web.MVC.Layouts;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Layouts/FlexSharedLayout_.cshtml")]
    public partial class FlexSharedLayout_ : System.Web.Mvc.WebViewPage<dynamic>
    {
        public FlexSharedLayout_()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");


WriteLiteral(@"
<!DOCTYPE html>

<html>
   <head>
      <!-- Required for IE compatibility -->
      <meta http-equiv=""X-UA-Compatible"" content=""IE=11; IE=10; IE=9; IE=EDGE"" />
      <meta http-equiv=""Content-Type"" content=""text/html; charset=utf-8"" />
      <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"" />

      <link href=""");


            
            #line 15 "..\..\Layouts\FlexSharedLayout_.cshtml"
              Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Styles/fonts.min.css\" rel=\"stylesheet\" media=\"screen\" />\r\n      <link href=\"");


            
            #line 16 "..\..\Layouts\FlexSharedLayout_.cshtml"
              Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Styles/jquery-ui.min.css\" rel=\"stylesheet\" media=\"screen\" />\r\n      \r\n      <!--" +
" \"DoNotCacheTag\" is needed to avoid issues with IE9 -->\r\n      <link href=\"");


            
            #line 19 "..\..\Layouts\FlexSharedLayout_.cshtml"
              Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Styles/bootstrap.min.css");


            
            #line 19 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                                                 Write(FlexCoreLayout.DoNotCacheTag);

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" media=\"screen\" />\r\n      <link href=\"");


            
            #line 20 "..\..\Layouts\FlexSharedLayout_.cshtml"
              Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Styles/bootstrap-datepicker3.min.css\" rel=\"stylesheet\" media=\"screen\" />\r\n      " +
"<link href=\"");


            
            #line 21 "..\..\Layouts\FlexSharedLayout_.cshtml"
              Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Styles/bootstrap-switch.min.css\" rel=\"stylesheet\" media=\"screen\" />\r\n      \r\n   " +
"   <link href=\"");


            
            #line 23 "..\..\Layouts\FlexSharedLayout_.cshtml"
              Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Styles/flex.min.css\" rel=\"stylesheet\" media=\"screen\" />\r\n      \r\n      <link hre" +
"f=\"");


            
            #line 25 "..\..\Layouts\FlexSharedLayout_.cshtml"
              Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Styles/bootstrap-table.min.css\" rel=\"stylesheet\" media=\"screen\" />\r\n      <link " +
"href=\"");


            
            #line 26 "..\..\Layouts\FlexSharedLayout_.cshtml"
              Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Styles/select2.min.css");


            
            #line 26 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                                               Write(FlexCoreLayout.DoNotCacheTag);

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" media=\"screen\" />\r\n      <link href=\"");


            
            #line 27 "..\..\Layouts\FlexSharedLayout_.cshtml"
              Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Styles/select2-bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\" />\r\n\r\n      <!" +
"-- Respond.js and html5shiv must be put AFTER CSS for Bootstrap -->\r\n      <!--[" +
"if lt IE 9]>  \r\n         <script src=\"");


            
            #line 31 "..\..\Layouts\FlexSharedLayout_.cshtml"
                  Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/html5shiv.min.js\"></script>\r\n         <script src=\"");


            
            #line 32 "..\..\Layouts\FlexSharedLayout_.cshtml"
                  Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/respond.min.js\"></script>\r\n      <![endif]-->\r\n      \r\n      <script typ" +
"e=\"text/javascript\" src=\"");


            
            #line 35 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/base64.min.js\"></script>\r\n\r\n      <script type=\"text/javascript\" src=\"");


            
            #line 37 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/jquery-2.1.1.min.js\"></script>\r\n      <script type=\"text/javascript\" src" +
"=\"");


            
            #line 38 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/underscore.min.js\"></script>\r\n      <script type=\"text/javascript\" src=\"" +
"");


            
            #line 39 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/backbone.min.js\"></script>\r\n\r\n      <script type=\"text/javascript\" src=\"" +
"");


            
            #line 41 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/jquery-ui.min.js\"></script>\r\n      <script type=\"text/javascript\" src=\"");


            
            #line 42 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/jquery.unobtrusive-ajax.min.js\"></script>\r\n      <script type=\"text/java" +
"script\" src=\"");


            
            #line 43 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/spin.min.js\"></script>\r\n\r\n      <script type=\"text/javascript\" src=\"");


            
            #line 45 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/bootstrap.min.js\"></script>\r\n      <script type=\"text/javascript\" src=\"");


            
            #line 46 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/bootstrap-hover-dropdown.min.js\"></script>\r\n      <script type=\"text/jav" +
"ascript\" src=\"");


            
            #line 47 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/bootstrap-datepicker.min.js\"></script>\r\n      <script type=\"text/javascr" +
"ipt\" src=\"");


            
            #line 48 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/bootstrap-maxlength.min.js\"></script>\r\n      <script type=\"text/javascri" +
"pt\" src=\"");


            
            #line 49 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/bootstrap-switch.min.js\"></script>\r\n\r\n      <script type=\"text/javascrip" +
"t\" src=\"");


            
            #line 51 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/bootstrap-table.min.js\"></script>\r\n      <script type=\"text/javascript\" " +
"src=\"");


            
            #line 52 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/select2.min.js\"></script>\r\n      \r\n      <!-- Custom scripts, use DoNotC" +
"acheTag to allow emergency updates! -->\r\n      <script type=\"text/javascript\" sr" +
"c=\"");


            
            #line 55 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/flex.min.js");


            
            #line 55 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                                                                    Write(FlexCoreLayout.DoNotCacheTag);

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n\r\n      <script type=\"text/javascript\" src=\"");


            
            #line 57 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                      Write(FlexCoreLayout.MyFlexPath);

            
            #line default
            #line hidden
WriteLiteral("/Scripts/autocompletes.min.js");


            
            #line 57 "..\..\Layouts\FlexSharedLayout_.cshtml"
                                                                                               Write(FlexCoreLayout.DoNotCacheTag);

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n      \r\n      <script type=\"text/javascript\">\r\n         // JS settin" +
"gs\r\n         settings.rootPath = \"");


            
            #line 61 "..\..\Layouts\FlexSharedLayout_.cshtml"
                         Write(FlexCoreLayout.RootPath);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n         settings.flexPath = \"");


            
            #line 62 "..\..\Layouts\FlexSharedLayout_.cshtml"
                         Write(FlexCoreLayout.FlexPath);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n         settings.myFlexPath = \"");


            
            #line 63 "..\..\Layouts\FlexSharedLayout_.cshtml"
                           Write(FlexCoreLayout.MyFlexPath);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n      </script>\r\n      \r\n      ");


            
            #line 66 "..\..\Layouts\FlexSharedLayout_.cshtml"
 Write(RenderSection("HeadSection"));

            
            #line default
            #line hidden
WriteLiteral("\r\n   </head>\r\n   \r\n   <body>\r\n      ");


            
            #line 70 "..\..\Layouts\FlexSharedLayout_.cshtml"
 Write(RenderSection("BodySection"));

            
            #line default
            #line hidden
WriteLiteral("\r\n   </body>\r\n\r\n</html>");


        }
    }
}
#pragma warning restore 1591
