#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEX.Web.MVC.Layouts.Pages
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
    using FLEX.Web.MVC.Controls.PageElements;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Layouts/Pages/FlexVerticalSearchLayout_.cshtml")]
    public partial class FlexVerticalSearchLayout_ : System.Web.Mvc.WebViewPage<dynamic>
    {
        public FlexVerticalSearchLayout_()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n");


            
            #line 6 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
  
   Layout = "~/Layouts/Pages/FlexPageLayout_.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("HeadSection", () => {

WriteLiteral("  \r\n   ");


            
            #line 11 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
Write(RenderSection("HeadSection"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("BodySection", () => {

WriteLiteral(@"
   
   <!-- Search Criteria (START) -->
   <div class=""col-xs-3"">
      <div id=""search-criteria-panel"" class=""panel panel-primary"">
         <div class=""panel-heading"">
            <h3 class=""panel-title"">Search Criteria</h3>
         </div>
         
         <div class=""page-working-area"">
            ");


            
            #line 24 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
       Write(RenderSection("SearchCriteriaSection"));

            
            #line default
            #line hidden
WriteLiteral(@"
         </div>
         
         <div class=""panel-footer"">
            <div class=""row"">
               <div class=""col-xs-4 text-left"">
                  <button type=""button"" id=""btn-hide-search-criteria"" class=""btn btn-info"">
                     <span id=""icon-hide-search-criteria"" class=""glyphicon glyphicon-arrow-left padded-icon""></span>Hide
                  </button>
               </div>
               <div class=""col-xs-4 text-center"">
                  
               </div>
               <div class=""col-xs-4 text-right"">
                  <button type=""button"" id=""btn-clear-search-criteria"" class=""btn btn-primary"">
                     <span id=""icon-clear-search-criteria"" class=""glyphicon glyphicon-trash padded-icon""></span>Clear
                  </button>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- Search Criteria (END) -->
   
   <!-- Data Grid (START) -->
   <div class=""col-xs-9"">
      <div id=""data-grid-panel"" class=""panel panel-primary"">
         <div class=""panel-heading"">
            <h3 class=""panel-title"">TITLE</h3>
         </div>
         
         <div class=""page-working-area"">
            ");


            
            #line 56 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
       Write(RenderSection("DataGridSection"));

            
            #line default
            #line hidden
WriteLiteral("\r\n         </div>\r\n         \r\n         <div class=\"panel-footer\">\r\n            \r\n" +
"         </div>\r\n      </div>\r\n   </div>\r\n   <!-- Data Grid (END) -->\r\n\r\n");


});


        }
    }
}
#pragma warning restore 1591
