#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEX.Web.MVC.Layouts.Pages
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
    using FLEX.Web.MVC.Controls.PageElements;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Layouts/Pages/FlexVerticalSearchLayout_.cshtml")]
    public partial class FlexVerticalSearchLayout_ : System.Web.Mvc.WebViewPage<dynamic>
    {
        public FlexVerticalSearchLayout_()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n");


            
            #line 6 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
  
   ViewBag.SearchCriteriaPanelCssClass = "col-xs-12 col-sm-4-5 col-md-3-5 col-lg-2-5";
   ViewBag.DataGridPanelCssClass = "col-xs-12 col-sm-7-5 col-md-8-5 col-lg-9-5";
   ViewBag.ExpandedDataGridPanelCssClass = "col-xs-11-5";


            
            #line default
            #line hidden
WriteLiteral(@"

   <script type=""text/javascript"">

      $(document).ready(function() {

         $(""#btn-hide-search-criteria"").click(function () {
            var searchCriteriaPanel = $(""#search-criteria-panel"");
            var btnCriteriaPlaceholder = $(""#btn-criteria-placeholder"");
            var dataGridPanel = $(""#data-grid-panel"");

            if (!searchCriteriaPanel.hasClass('hidden')) {
               // Collapse Search criteria and expand Data grid
               searchCriteriaPanel.addClass(""hidden"");
               btnCriteriaPlaceholder.removeClass(""hidden"");
               var plHeight = dataGridPanel.children().outerHeight();
               btnCriteriaPlaceholder.css({ height: plHeight + ""px"", paddingTop: plHeight / 2 + ""px"" });
               dataGridPanel.switchClass(""");


            
            #line 28 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
                                     Write(ViewBag.DataGridPanelCssClass);

            
            #line default
            #line hidden
WriteLiteral("\", \"");


            
            #line 28 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
                                                                       Write(ViewBag.ExpandedDataGridPanelCssClass);

            
            #line default
            #line hidden
WriteLiteral(@""", 0);
            }
         });

         $(""#btn-criteria-placeholder"").click(function () {
            var searchCriteriaPanel = $(""#search-criteria-panel"");
            var btnCriteriaPlaceholder = $(""#btn-criteria-placeholder"");
            var dataGridPanel = $(""#data-grid-panel"");

            if (searchCriteriaPanel.hasClass('hidden')) {
               // Collapse Data Grid and expand Search Criteria
               dataGridPanel.switchClass(""");


            
            #line 39 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
                                     Write(ViewBag.ExpandedDataGridPanelCssClass);

            
            #line default
            #line hidden
WriteLiteral("\", \"");


            
            #line 39 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
                                                                               Write(ViewBag.DataGridPanelCssClass);

            
            #line default
            #line hidden
WriteLiteral("\", 0);\r\n               btnCriteriaPlaceholder.addClass(\"hidden\");\r\n              " +
" searchCriteriaPanel.removeClass(\"hidden\");\r\n            }\r\n         });\r\n      " +
"});\r\n\r\n      function onSearchCriteriumCollapsing(id) {\r\n         var pageName =" +
" \"");


            
            #line 47 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
                    Write(VirtualPath);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n         var userName = \"");


            
            #line 48 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
                    Write(HttpContext.Current.User.Identity.Name);

            
            #line default
            #line hidden
WriteLiteral(@""";
         var key = userName + ""_VerticalSearch_"" + pageName;
         var controlStatus = JSON.parse(localStorage.getItem(key));

         // If no exists _statusControl, create the array _statusControl
         if (controlStatus == null) {
            controlStatus = [];
         }

         if ($(""#icr"" + id).hasClass('glyphicon-chevron-down')) {
            $(""#icr"" + id).switchClass('glyphicon-chevron-down', 'glyphicon-chevron-up');
            var elemt = _.find(controlStatus, function (i) { return i.id == id; });
            if (elemt == null) {
               controlStatus.push({ id: id, closed: false, index: -1 });
            } else {
               elemt.closed = false;
            }

         } else if ($(""#icr"" + id).hasClass('glyphicon-chevron-up')) {
            $(""#icr"" + id).switchClass('glyphicon-chevron-up', 'glyphicon-chevron-down');
            var elemt = _.find(controlStatus, function (i) { return i.id == id; });
            if (elemt == null) {
               controlStatus.push({ id: id, closed: true, index: -1 });
            } else {
               elemt.closed = true;
            }
         }

         // Save in the localStorage the controlStatus array.
         localStorage.setItem(key, JSON.stringify(controlStatus));
      }
   </script>



   <!-- Search Criteria (START) -->
   <div id=""search-criteria-panel"" class=""");


            
            #line 84 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
                                     Write(ViewBag.SearchCriteriaPanelCssClass);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n      <div class=\"panel panel-primary\">\r\n         <div class=\"panel-heading\">" +
"\r\n            <h3 class=\"panel-title\">Search Criteria pppppppppppppppp</h3>\r\n   " +
"      </div>\r\n         \r\n         <div class=\"panel-body page-working-area\">\r\n  " +
"          ");


            
            #line 91 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
       Write(RenderSection("SearchCriteriaSection"));

            
            #line default
            #line hidden
WriteLiteral(@"
         </div>
         
         <div class=""panel-footer"">
            <div class=""row"">
               <div class=""col-xs-4 text-left"">
                  <button type=""button"" id=""btn-hide-search-criteria"" class=""btn btn-info"">
                     <span id=""icon-hide-search-criteria"" class=""glyphicon glyphicon-arrow-left padded-icon""></span>Hide
                  </button>
               </div>
               <div class=""col-xs-4 text-center"">
                  
               </div>
               <div class=""col-xs-4 text-right"">
                  <button type=""button"" id=""btn-clear-search-criteria"" class=""btn btn-primary"">
                     <span id=""icon-clear-search-criteria"" class=""glyphicon glyphicon-trash padded-icon""></span>Clear
                  </button>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- Search Criteria (END) -->
   
   <!-- Search Criteria Placeholder (START) -->
   <button type=""button"" id=""btn-criteria-placeholder"" class=""hidden col-xs-0-5 btn btn-primary"">
      <span class=""glyphicon glyphicon-arrow-right""></span>
   </button>
   <!-- Search Criteria Placeholder (END) -->

   <!-- Data Grid (START) -->
   <div id=""data-grid-panel"" class=""");


            
            #line 122 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
                               Write(ViewBag.DataGridPanelCssClass);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n      <div class=\"panel panel-primary\">\r\n         <div class=\"panel-heading\">" +
"\r\n            <h3 class=\"panel-title\">TITLE</h3>\r\n         </div>\r\n         \r\n  " +
"       <div class=\"page-working-area\">\r\n            ");


            
            #line 129 "..\..\Layouts\Pages\FlexVerticalSearchLayout_.cshtml"
       Write(RenderSection("DataGridSection"));

            
            #line default
            #line hidden
WriteLiteral("\r\n         </div>\r\n         \r\n         <div class=\"panel-footer\">\r\n            \r\n" +
"         </div>\r\n      </div>\r\n   </div>\r\n   <!-- Data Grid (END) -->\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
