//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FLEX.Extensions.TestDataAccess", "CandidateAttended", "Candidate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FLEX.Extensions.TestDataAccess.Candidate), "School", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FLEX.Extensions.TestDataAccess.School))]
[assembly: EdmRelationshipAttribute("FLEX.Extensions.TestDataAccess", "FK_Candidate_Gender", "Gender", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FLEX.Extensions.TestDataAccess.Gender), "Candidate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FLEX.Extensions.TestDataAccess.Candidate))]

#endregion

namespace FLEX.Extensions.TestDataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DataContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DataContext object using the connection string found in the 'DataContext' section of the application configuration file.
        /// </summary>
        public DataContext() : base("name=DataContext", "DataContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataContext object.
        /// </summary>
        public DataContext(string connectionString) : base(connectionString, "DataContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataContext object.
        /// </summary>
        public DataContext(EntityConnection connection) : base(connection, "DataContext")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<School> Schools
        {
            get
            {
                if ((_Schools == null))
                {
                    _Schools = base.CreateObjectSet<School>("Schools");
                }
                return _Schools;
            }
        }
        private ObjectSet<School> _Schools;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Candidate> Candidates
        {
            get
            {
                if ((_Candidates == null))
                {
                    _Candidates = base.CreateObjectSet<Candidate>("Candidates");
                }
                return _Candidates;
            }
        }
        private ObjectSet<Candidate> _Candidates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Gender> Genders
        {
            get
            {
                if ((_Genders == null))
                {
                    _Genders = base.CreateObjectSet<Gender>("Genders");
                }
                return _Genders;
            }
        }
        private ObjectSet<Gender> _Genders;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Schools EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSchools(School school)
        {
            base.AddObject("Schools", school);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Candidates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCandidates(Candidate candidate)
        {
            base.AddObject("Candidates", candidate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Genders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGenders(Gender gender)
        {
            base.AddObject("Genders", gender);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FLEX.Extensions.TestDataAccess", Name="Candidate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Candidate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Candidate object.
        /// </summary>
        /// <param name="cand_Id">Initial value of the Cand_Id property.</param>
        /// <param name="cand_Name">Initial value of the Cand_Name property.</param>
        /// <param name="cand_Surname">Initial value of the Cand_Surname property.</param>
        /// <param name="cand_Email">Initial value of the Cand_Email property.</param>
        public static Candidate CreateCandidate(global::System.Int32 cand_Id, global::System.String cand_Name, global::System.String cand_Surname, global::System.String cand_Email)
        {
            Candidate candidate = new Candidate();
            candidate.Cand_Id = cand_Id;
            candidate.Cand_Name = cand_Name;
            candidate.Cand_Surname = cand_Surname;
            candidate.Cand_Email = cand_Email;
            return candidate;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cand_Id
        {
            get
            {
                return _Cand_Id;
            }
            set
            {
                if (_Cand_Id != value)
                {
                    OnCand_IdChanging(value);
                    ReportPropertyChanging("Cand_Id");
                    _Cand_Id = StructuralObject.SetValidValue(value, "Cand_Id");
                    ReportPropertyChanged("Cand_Id");
                    OnCand_IdChanged();
                }
            }
        }
        private global::System.Int32 _Cand_Id;
        partial void OnCand_IdChanging(global::System.Int32 value);
        partial void OnCand_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cand_Name
        {
            get
            {
                return _Cand_Name;
            }
            set
            {
                OnCand_NameChanging(value);
                ReportPropertyChanging("Cand_Name");
                _Cand_Name = StructuralObject.SetValidValue(value, false, "Cand_Name");
                ReportPropertyChanged("Cand_Name");
                OnCand_NameChanged();
            }
        }
        private global::System.String _Cand_Name;
        partial void OnCand_NameChanging(global::System.String value);
        partial void OnCand_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cand_Surname
        {
            get
            {
                return _Cand_Surname;
            }
            set
            {
                OnCand_SurnameChanging(value);
                ReportPropertyChanging("Cand_Surname");
                _Cand_Surname = StructuralObject.SetValidValue(value, false, "Cand_Surname");
                ReportPropertyChanged("Cand_Surname");
                OnCand_SurnameChanged();
            }
        }
        private global::System.String _Cand_Surname;
        partial void OnCand_SurnameChanging(global::System.String value);
        partial void OnCand_SurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cand_Email
        {
            get
            {
                return _Cand_Email;
            }
            set
            {
                OnCand_EmailChanging(value);
                ReportPropertyChanging("Cand_Email");
                _Cand_Email = StructuralObject.SetValidValue(value, false, "Cand_Email");
                ReportPropertyChanged("Cand_Email");
                OnCand_EmailChanged();
            }
        }
        private global::System.String _Cand_Email;
        partial void OnCand_EmailChanging(global::System.String value);
        partial void OnCand_EmailChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FLEX.Extensions.TestDataAccess", "CandidateAttended", "School")]
        public EntityCollection<School> Schools
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<School>("FLEX.Extensions.TestDataAccess.CandidateAttended", "School");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<School>("FLEX.Extensions.TestDataAccess.CandidateAttended", "School", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FLEX.Extensions.TestDataAccess", "FK_Candidate_Gender", "Gender")]
        public Gender Gender
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gender>("FLEX.Extensions.TestDataAccess.FK_Candidate_Gender", "Gender").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gender>("FLEX.Extensions.TestDataAccess.FK_Candidate_Gender", "Gender").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Gender> GenderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gender>("FLEX.Extensions.TestDataAccess.FK_Candidate_Gender", "Gender");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Gender>("FLEX.Extensions.TestDataAccess.FK_Candidate_Gender", "Gender", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FLEX.Extensions.TestDataAccess", Name="Gender")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Gender : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Gender object.
        /// </summary>
        /// <param name="gend_Id">Initial value of the Gend_Id property.</param>
        /// <param name="gend_Description">Initial value of the Gend_Description property.</param>
        public static Gender CreateGender(global::System.Int32 gend_Id, global::System.String gend_Description)
        {
            Gender gender = new Gender();
            gender.Gend_Id = gend_Id;
            gender.Gend_Description = gend_Description;
            return gender;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Gend_Id
        {
            get
            {
                return _Gend_Id;
            }
            set
            {
                if (_Gend_Id != value)
                {
                    OnGend_IdChanging(value);
                    ReportPropertyChanging("Gend_Id");
                    _Gend_Id = StructuralObject.SetValidValue(value, "Gend_Id");
                    ReportPropertyChanged("Gend_Id");
                    OnGend_IdChanged();
                }
            }
        }
        private global::System.Int32 _Gend_Id;
        partial void OnGend_IdChanging(global::System.Int32 value);
        partial void OnGend_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gend_Description
        {
            get
            {
                return _Gend_Description;
            }
            set
            {
                OnGend_DescriptionChanging(value);
                ReportPropertyChanging("Gend_Description");
                _Gend_Description = StructuralObject.SetValidValue(value, false, "Gend_Description");
                ReportPropertyChanged("Gend_Description");
                OnGend_DescriptionChanged();
            }
        }
        private global::System.String _Gend_Description;
        partial void OnGend_DescriptionChanging(global::System.String value);
        partial void OnGend_DescriptionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FLEX.Extensions.TestDataAccess", "FK_Candidate_Gender", "Candidate")]
        public EntityCollection<Candidate> Candidates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Candidate>("FLEX.Extensions.TestDataAccess.FK_Candidate_Gender", "Candidate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Candidate>("FLEX.Extensions.TestDataAccess.FK_Candidate_Gender", "Candidate", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FLEX.Extensions.TestDataAccess", Name="School")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class School : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new School object.
        /// </summary>
        /// <param name="schl_Id">Initial value of the Schl_Id property.</param>
        /// <param name="schl_Description">Initial value of the Schl_Description property.</param>
        public static School CreateSchool(global::System.Int32 schl_Id, global::System.String schl_Description)
        {
            School school = new School();
            school.Schl_Id = schl_Id;
            school.Schl_Description = schl_Description;
            return school;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Schl_Id
        {
            get
            {
                return _Schl_Id;
            }
            set
            {
                if (_Schl_Id != value)
                {
                    OnSchl_IdChanging(value);
                    ReportPropertyChanging("Schl_Id");
                    _Schl_Id = StructuralObject.SetValidValue(value, "Schl_Id");
                    ReportPropertyChanged("Schl_Id");
                    OnSchl_IdChanged();
                }
            }
        }
        private global::System.Int32 _Schl_Id;
        partial void OnSchl_IdChanging(global::System.Int32 value);
        partial void OnSchl_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Schl_Description
        {
            get
            {
                return _Schl_Description;
            }
            set
            {
                OnSchl_DescriptionChanging(value);
                ReportPropertyChanging("Schl_Description");
                _Schl_Description = StructuralObject.SetValidValue(value, false, "Schl_Description");
                ReportPropertyChanged("Schl_Description");
                OnSchl_DescriptionChanged();
            }
        }
        private global::System.String _Schl_Description;
        partial void OnSchl_DescriptionChanging(global::System.String value);
        partial void OnSchl_DescriptionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FLEX.Extensions.TestDataAccess", "CandidateAttended", "Candidate")]
        public EntityCollection<Candidate> Candidates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Candidate>("FLEX.Extensions.TestDataAccess.CandidateAttended", "Candidate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Candidate>("FLEX.Extensions.TestDataAccess.CandidateAttended", "Candidate", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FLEX.Extensions.TestDataAccess", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }

    #endregion

}
