//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by XsdClassGen.tt.
//     Runtime Version: 4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

using System.IO;
using System.Xml;
using System.Xml.Serialization;

namespace FLEX.Common.XmlSchemas.MenuEntries
{
	public partial class Menu
	{
		public static Menu DeserializeFrom(string str)
		{
			var serializer = new XmlSerializer(typeof(Menu));
		    using (var stream = new StringReader(str)) {
			    return serializer.Deserialize(stream) as Menu;
		    }
		}

		public static Menu DeserializeFrom(Stream stream)
		{
			var serializer = new XmlSerializer(typeof(Menu));
			return serializer.Deserialize(stream) as Menu;
		}

		public static Menu DeserializeFrom(TextReader reader)
		{
			var serializer = new XmlSerializer(typeof(Menu));
			return serializer.Deserialize(reader) as Menu;
		}

		public static Menu DeserializeFrom(XmlReader reader)
		{
			var serializer = new XmlSerializer(typeof(Menu));
			return serializer.Deserialize(reader) as Menu;
		}

		public void SerializeTo(ref string str)
		{
			var serializer = new XmlSerializer(typeof(Menu));
            using (var stream = new StringWriter()) {
			    serializer.Serialize(stream, this);
                str = stream.ToString();
            }
		}

		public void SerializeTo(Stream stream)
		{
			var serializer = new XmlSerializer(typeof(Menu));
			serializer.Serialize(stream, this);
		}

		public void SerializeTo(TextWriter writer)
		{
			var serializer = new XmlSerializer(typeof(Menu));
			serializer.Serialize(writer, this);
		}

		public void SerializeTo(XmlWriter writer)
		{
			var serializer = new XmlSerializer(typeof(Menu));
			serializer.Serialize(writer, this);
		}
	}
}
