#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finsa.Caravan.Mvc.Controls.DataVisualization
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 4 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
    using Finsa.Caravan.Extensions;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
    using Finsa.Caravan.Mvc.Controls.DataVisualization;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class BootstrapTable_
    {

public static System.Web.WebPages.HelperResult BootstrapTable(this AjaxHelper ajaxHelper, BootstrapTableOptions options)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 10 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "   <script type=\"text/javascript\" defer=\"defer\">\r\n      $(document).ready(functio" +
"n() {\r\n         $(\'#");



#line 13 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ID);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\').bootstrapTable();\r\n      });\r\n   </script>\r\n");



#line 16 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "   <div id=\"");



#line 17 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ID);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "-container\">\r\n      ");



#line 18 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, ajaxHelper.ActionLink("update-grid", "InitializeSearchGrid", new {searchCriteriaJson = "", pageIndex = 1}, new AjaxOptions
      {
         HttpMethod = "GET",
         InsertionMode = InsertionMode.Replace,
         UpdateTargetId = @options.ID + "-container"
      }, new {id = "update-grid", @class = "hidden"}));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n\r\n      <table id=\"");



#line 25 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ID);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" class=\"table table-striped table-condensed table-hover\" data-toggle=\"table\"\r\n  " +
"           data-pagination=\"");



#line 26 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ShowPagination.ToJavaScriptBoolean());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" \r\n             data-search=\"");



#line 27 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ShowSearchBox.ToJavaScriptBoolean());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"\r\n             data-show-columns=\"true\"\r\n             data-show-export=\"");



#line 29 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, options.ShowExportButton.ToJavaScriptBoolean());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n         \r\n         <thead>\r\n            <tr>\r\n");



#line 33 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
                foreach (var column in options.Columns)
               {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                  <th data-field=\"");



#line 35 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, column.ID);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-align=\"");



#line 35 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
               WebViewPage.WriteTo(@__razor_helper_writer, column.HAlign);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-valign=\"");



#line 35 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
                                            WebViewPage.WriteTo(@__razor_helper_writer, column.VAlign);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-sortable=\"");



#line 35 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
                                                                           WebViewPage.WriteTo(@__razor_helper_writer, column.Sortable.ToJavaScriptBoolean());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n                     ");



#line 36 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, column.Header);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                  </th>\r\n");



#line 38 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
               }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </tr>\r\n         </thead>\r\n      \r\n         <tbody>\r\n");



#line 43 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
             foreach (var item in options.Items)
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "               <tr>\r\n");



#line 46 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
                   foreach (var column in options.Columns)
                  {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                     <td>\r\n                        ");



#line 49 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, column.Control(item));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                     </td>\r\n");



#line 51 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
                  }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "               </tr>\r\n");



#line 53 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"
            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "         </tbody>\r\n      </table>\r\n   </div>\r\n");



#line 57 "..\..\Controls\DataVisualization\BootstrapTable_.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
