#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEX.Web.MVC.Layouts.Popups
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Layouts/Popups/Popup.cshtml")]
    public partial class Popup : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Popup()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");


            
            #line 4 "..\..\Layouts\Popups\Popup.cshtml"
  
   Layout = "~/Layouts/Common_.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"container-fluid\">\r\n   POPUP\r\n   ");


            
            #line 10 "..\..\Layouts\Popups\Popup.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
