-- REPLACE 'mydb' WITH DB NAME

CREATE TABLE mydb.crvn_idn_TABNAME
(
     CCLI_ID                        NUMBER(19)      NOT NULL
   , CCLI_ENABLED                   NVARCHAR2(8)    NOT NULL
   , CCLI_CLIENT_ID                 NUMBER(1)       NOT NULL
   , CCLI_CLIENT_NAME               NUMBER(3)       NOT NULL
   , CCLI_LOGO_URI                  NUMBER(7)       NOT NULL
   , CCLI_REQUIRE_CONSENT           NUMBER(7)       NOT NULL
   , CCLI_ALLOW_REMEMBER_CONSENT    NUMBER(7)       NOT NULL
   , CCLI_FLOW                      NUMBER(7)       NOT NULL
   , CCLI_ALLOW_CLIENT_CREDS_ONLY   NUMBER(7)       NOT NULL
   , CCLI_ALLOW_ACCESS_TO_ALL_SCPS  NUMBER(7)       NOT NULL
   , CCLI_IDENTITY_TOKEN_LIFETIME   NUMBER(7)       NOT NULL
   , CCLI_ACCESS_TOKEN_LIFETIME     NUMBER(7)       NOT NULL
   , CCLI_AUTH_CODE_LIFETIME        NUMBER(7)       NOT NULL
   , CCLI_ABS_REFR_TOKEN_LIFETIME   NUMBER(7)       NOT NULL
   , CCLI_SLID_REFR_TOKEN_LIFETIME  NUMBER(7)       NOT NULL
   , CCLI_REFRESH_TOKEN_USAGE       NUMBER(7)       NOT NULL
   , CCLI_UPD_ACCESS_TOKEN_ON_REFR  NUMBER(7)       NOT NULL
   , CCLI_REFRESH_TOKEN_EXPIRATION  NUMBER(7)       NOT NULL
   , CCLI_ACCESS_TOKEN_TYPE         NUMBER(7)       NOT NULL
   , CCLI_ENABLE_LOCAL_LOGIN        NUMBER(7)       NOT NULL
   , CCLI_INCLUDE_JWT_ID            NUMBER(7)       NOT NULL
   , CCLI_ALWAYS_SEND_CLIENT_CLAIMS NUMBER(7)       NOT NULL
   , CCLI_PREFIX_CLIENT_CLAIMS      NUMBER(7)       NOT NULL
   , CCLI_ALLOW_ACCESS_TO_ALL_GRTP  NUMBER(7)       NOT NULL

   , CHECK (clos_type IN ('debug', 'trace', 'info', 'warn', 'error', 'fatal')) ENABLE

   , CONSTRAINT pk_crvn_idn_TABNAME PRIMARY KEY (CCLI_ID) ENABLE
   , CONSTRAINT uk_crvn_idn_TABNAME UNIQUE (CCLI_CLIENT_ID) ENABLE
   , CONSTRAINT fk_crvnidnTABNAME_ FOREIGN KEY (capp_id) REFERENCES mydb.crvn_sec_apps (capp_id) ON DELETE CASCADE ENABLE
);
