-- REPLACE 'mydb' WITH DB NAME

CREATE TABLE mydb.crvn_idn_clients
(
     CCLI_ID                        NUMBER(10)      NOT NULL
   , CCLI_ENABLED                   NUMBER(1)       NOT NULL
   , CCLI_CLIENT_ID                 NVARCHAR2(200)  NOT NULL
   , CCLI_CLIENT_NAME               NVARCHAR2(200)  NOT NULL
   , CCLI_CLIENT_URI                NVARCHAR2(2000) NOT NULL
   , CCLI_LOGO_URI                  NVARCHAR2(2000)
   , CCLI_REQUIRE_CONSENT           NUMBER(1)       NOT NULL
   , CCLI_ALLOW_REMEMBER_CONSENT    NUMBER(1)       NOT NULL
   , CCLI_FLOW                      NUMBER(3)       NOT NULL
   , CCLI_ALLOW_CLIENT_CREDS_ONLY   NUMBER(1)       NOT NULL
   , CCLI_ALLOW_ACCESS_TO_ALL_SCPS  NUMBER(1)       NOT NULL
   , CCLI_IDENTITY_TOKEN_LIFETIME   NUMBER(10)      NOT NULL
   , CCLI_ACCESS_TOKEN_LIFETIME     NUMBER(10)      NOT NULL
   , CCLI_AUTH_CODE_LIFETIME        NUMBER(10)      NOT NULL
   , CCLI_ABS_REFR_TOKEN_LIFETIME   NUMBER(10)      NOT NULL
   , CCLI_SLID_REFR_TOKEN_LIFETIME  NUMBER(10)      NOT NULL
   , CCLI_REFRESH_TOKEN_USAGE       NUMBER(3)       NOT NULL
   , CCLI_UPD_ACCESS_TOKEN_ON_REFR  NUMBER(1)       NOT NULL
   , CCLI_REFRESH_TOKEN_EXPIRATION  NUMBER(3)       NOT NULL
   , CCLI_ACCESS_TOKEN_TYPE         NUMBER(3)       NOT NULL
   , CCLI_ENABLE_LOCAL_LOGIN        NUMBER(1)       NOT NULL
   , CCLI_INCLUDE_JWT_ID            NUMBER(1)       NOT NULL
   , CCLI_ALWAYS_SEND_CLIENT_CLAIMS NUMBER(1)       NOT NULL
   , CCLI_PREFIX_CLIENT_CLAIMS      NUMBER(1)       NOT NULL
   , CCLI_ALLOW_ACCESS_TO_ALL_GRTP  NUMBER(1)       NOT NULL

   , CHECK (CCLI_IDENTITY_TOKEN_LIFETIME > 0) ENABLE
   , CHECK (CCLI_ACCESS_TOKEN_LIFETIME > 0) ENABLE
   , CHECK (CCLI_AUTH_CODE_LIFETIME > 0) ENABLE
   , CHECK (CCLI_ABS_REFR_TOKEN_LIFETIME > 0) ENABLE
   , CHECK (CCLI_SLID_REFR_TOKEN_LIFETIME > 0) ENABLE

   , CONSTRAINT pk_crvn_idn_clients PRIMARY KEY (CCLI_ID) ENABLE
   , CONSTRAINT uk_crvn_idn_clients UNIQUE (CCLI_CLIENT_ID) ENABLE
);
