//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEX.Web.Pages.Templates {
    
    
    public partial class VerticalSearch {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new FLEX.Web.MasterPages.VerticalSearch Master {
            get {
                return ((FLEX.Web.MasterPages.VerticalSearch)(base.Master));
            }
        }
    }
}
