-- REPLACE 'mydb' WITH DB NAME

CREATE OR REPLACE FORCE VIEW mydb."V_CARAVAN_LOG_SUMMARY" ("CAPP_ID", "CAPP_NAME", "CLOS_TYPE", "CLOG_ENTRIES", "CLOS_MAX_ENTRIES", "CLOG_MIN_DATE", "CLOG_MAX_DATE", "CLOG_DAYS", "CLOS_MAX_DAYS", "CLOS_ENABLED") AS
SELECT a."CAPP_ID",
       a."CAPP_NAME",
       s."CLOS_TYPE",
       COUNT(*) CLOG_ENTRIES,
       MAX(s."CLOS_MAX_ENTRIES") CLOS_MAX_ENTRIES,
       MIN(e."CLOG_DATE") CLOG_MIN_DATE,
       MAX(e."CLOG_DATE") CLOG_MAX_DATE,
       (TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP)) - TRUNC(MIN(e."CLOG_DATE"))) CLOG_DAYS,
       MAX(s."CLOS_DAYS") CLOS_MAX_DAYS,
       MAX(s."CLOS_ENABLED") CLOS_ENABLED
    FROM mydb.crvn_sec_apps a
    LEFT JOIN mydb.crvn_log_settings s ON s."CAPP_ID" = a."CAPP_ID"
    LEFT JOIN mydb.crvn_log_entries e ON e."CAPP_ID" = a."CAPP_ID" AND e."CLOS_TYPE" = s."CLOS_TYPE"
   GROUP BY a."CAPP_ID", a."CAPP_NAME", s."CLOS_TYPE"
   ORDER BY a."CAPP_NAME", s."CLOS_TYPE"